### PR TITLE
Moved fieldsKeys from a scope shared across all instances of pass to …

### PR DESCRIPTION
**Pull request by ianbale**
…a scope only shared across the field array within a single instance of pass

### CODE REVIEW

**Comment by alexandercerutti** [comment]
Please note that you are using spaces, while the project uses tabs. Please, convert them to tabs before. The diff is very big for this reason.

**Comment by ianbale** [comment]
I'll see if I can sort that tomorrow. Busy week for me...so if not, I'll make sure its doen by the end of the week.
I made a small change to pass.js. It's just to do with the call to create instantiate the arrays that changed.

**Comment by ianbale** [comment]
I've edited the file and swapped space indents back to tabs.

**Comment by ianbale** [comment]
New fork in my personal account setup and PR done.

**Comment by ianbale** [comment]
Hang on. I've made a mistake with this one...

**Comment by alexandercerutti** [comment]
I don't know what the f**k is going on, dude 😂

**Comment by ianbale** [comment]
I thought I had copied a file direct from the old repository to this one. But a line of code was present that should have been removed! Argh!!!!

Too much going on this end - as always!

**Comment by ianbale** [comment]
Let's abandon this PR. New PR is ready to roll.

**Pull request closed without merging**
