### PR TITLE
fix: relax validation rules for `major` in beacons

### LINKED ISSUE #157: Beacon minor/major validation is stricter than needed
## Running OS
macOS Ventura 13.4

## Running Node Version
Node v18.16.0

## Description
In the [Proximity Beacon Specification](https://www.blueupbeacons.com/docs/dev/Proximity%20Beacon%20Specification%20R1.pdf) and the [Getting Started with iBeacon guide](https://developer.apple.com/ibeacon/Getting-Started-with-iBeacon.pdf) from Apple, it's mentioned that major/minor are used purely as ways to divide beacons into categories, and the numbers themselves have no special meaning. So that if I own Starbucks, I can go ahead and give all the beacons in Starbucks `uuid: 'Starbucks'` and then give each country a `major` number, and each city a `minor` number. 

Currently, there is Joi validation on beacons that is unnecessarily too strict, asserting that:
* `major` has to be a positive number, which means that we can not set it to `0`.
* `major` has to be greater than `minor`, making `major: 1, minor: 1000` an invalid scenario according to `passkit-generator`, even though it's perfectly fine by the spec.

## Expected behavior
I expect the following to work without any errors:
```ts
pass.setBeacons({
  uuid: 'Starbucks',
  major: 0,
  minor: 1
});
```

### PR DESCRIPTION
**Pull request by AbdelrahmanHafez**
## Description
Fixes #157 
This PR relaxes `major` validation in beacons.

## Check relevant checkboxes
-   [x] I've run tests (through `npm test`) and they passed
-   [x] I generated a working Apple Wallet Pass after the change
-   [x] Provided examples keep working after the change
-   [ ] This improvement is or might be a breaking change

## Relevant information

Look at #157 for more information about the issue.
Example of a working pass: https://file.io/f1XIkfUuzC96

### CODE REVIEW

**Comment by AbdelrahmanHafez** [comment]
P.S: @alexandercerutti 
I couldn't run the tests even on _master_, Doing `npm i` followed by `npm test` gives me these errors:
```
> passkit-generator@3.1.10 test
> NODE_OPTIONS="--experimental-vm-modules --no-warnings" jest -c jest.config.cjs --silent

 FAIL  specs/PKPass.spec.cjs
  ● Test suite failed to run

    Cannot find module '../lib/PKPass' from 'specs/PKPass.spec.cjs'

       9 | const fs = require("node:fs");
      10 | const path = require("node:path");
    > 11 | const { default: PKPass } = require("../lib/PKPass");
         |                             ^
      12 |
      13 | /**
      14 |  * SIGNER_CERT, SIGNER_KEY, WWDR and SIGNER_KEY_PASSPHRASE are also set

      at Resolver._throwModNotFoundError (node_modules/jest-resolve/build/resolver.js:427:11)
      at Object.<anonymous> (specs/PKPass.spec.cjs:11:29)

 FAIL  specs/utils.spec.cjs
  ● Test suite failed to run

    Cannot find module '../lib/utils' from 'specs/utils.spec.cjs'

      1 | const { describe, expect, it } = require("@jest/globals");
    > 2 | const { processDate, removeHidden } = require("../lib/utils");
        |                                       ^
      3 |
      4 | describe("Utils", () => {
      5 | 	describe("removeHidden", () => {

      at Resolver._throwModNotFoundError (node_modules/jest-resolve/build/resolver.js:427:11)
      at Object.<anonymous> (specs/utils.spec.cjs:2:39)

Test Suites: 2 failed, 2 total
Tests:       0 total
Snapshots:   0 total
Time:        0.381 s
```

**Comment by alexandercerutti** [comment]
Can you please use the proposed template shown when opening a PullRequest?
You can also find it here: https://raw.githubusercontent.com/alexandercerutti/passkit-generator/master/.github/pull_request_template.md

Thank you!

**Comment by AbdelrahmanHafez** [comment]
@alexandercerutti 
I fixed the description, thanks!

**Review by alexandercerutti — APPROVED** [review]
LGTM! Will merge asap.

**Comment by alexandercerutti** [comment]
Released in [v3.1.11](https://github.com/alexandercerutti/passkit-generator/releases/tag/v3.1.11) 🎉

Thank you very much @AbdelrahmanHafez! If you could leave a ⭐️ on the project, that would be awesome!

**Pull request merged**
