### PR TITLE
added Buffer Model to README

### LINKED ISSUE #68: Add Buffer Model to README
Love this project! Super useful in the professional setting I'm working in :) The only thing that would have been helpful would be to have an example of the Buffer Model in the README or even the API docs as it took me a bit to find it in the Migration Guide! Again, thank you for all your work on this!

### PR DESCRIPTION
**Pull request by sarawarnock**
Took the buffer model usage example from the Migration Docs and added to README - it took me a bit to find the Migration Guide and what I needed was an example of the Buffer Model!! 

Closes #68

### CODE REVIEW

**Comment by alexandercerutti** [comment]
You surprised me with such speed! 😄
Thank you for your Pull Request.

What about having just an header ("Usage Examples") with smaller headings?

Something like this:
___

## Usage Examples

#### Folder Model

```typescript
// Here we show the code
```

____

#### Buffer Model

```typescript
// Here we show the code
```

**Comment by sarawarnock** [comment]
updated!! See what you think!

**Review by alexandercerutti — CHANGES_REQUESTED** [review]
Yeah, I like it!
May I ask you to replace this:

```
			"it.lproj/pass.strings": Buffer.from([ ... ])
		},
		// The rest will be the same as above 			
```

with

```
			"it.lproj/pass.strings": Buffer.from([ ... ])
		},
		// The rest will be the same as above 
		...	
	});
```

So we have the correct syntax? 😄 Unpaired brackets drive me crazy ahah
Thank you!

**Comment by sarawarnock** [comment]
Agreed! Fixed!

**Review by alexandercerutti — APPROVED** [review]

**Pull request merged**
