### PR TITLE
Issue 29 would be nice to use real dates

### PR DESCRIPTION
**Pull request by ianbale**
Re #29 

Modifications to permit the use of Date objects as well as date strings.

### CODE REVIEW

**Comment by alexandercerutti** [comment]
Sorry, I cannot accept this, because this would introduce a very big problem: a breaking change. Therefore I should increase the version and change the whole API for this. Moreover, we should introduce some tests for a thing like this.

Your idea is not bad, but I'm not that sure yet.
Anyway, I might introduce this in v2. I close this PR but will keep the reference in a projects card.

**Comment by alexandercerutti** [comment]
My Bad. This PR would not bring a breaking change. There is still the problem of spaces instead of tabs.
I'm reopening the PR.

**Comment by ianbale** [comment]
I've edited the file and swapped space indents back to tabs.

**Comment by alexandercerutti** [comment]
I would be okay with this edit, but you are again bringing with you the edits to FieldArray, which is not suggested. You have likely created a new branch starting from that.

I'd create a new branch to merge these changes so I can rebase, fix them and then apply. What do you think?

Anyway, I'd like you to notice that the commits you are making are not linked to your Github account but to an unknown git account. Do you know that? Also, I don't know what HazardourFrog is.

What about if you make another commit with the correct author so I can edit them all with the same author metadata?

**Comment by ianbale** [comment]
I have two GotHub accounts. A personal one (ianbale) and one for my company (hazardous frog). I figured it was more appropriate to use the company one since I'm using this for a company project. 

Easy enough to do a new fork in my own account and re-submit from there if you prefer. 

I accidentally merged the array changes into my master branch. I reverted that, but it reverts never seem to do what I expect! Would be cleaner to do a new fork...

Leave that with me. Won't take long.

**Comment by alexandercerutti** [comment]
I'm the idea that who creates the pull request commits, should appear in the statistics of contributors, not a different account. 😉 Anyway, it is not a problem.
Do not revert them, just rebase to remove the commits. Or, if you prefer it, you can do this:

https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by ianbale** [comment]
New fork in my personal account setup and PR done.

**Comment by ianbale** [comment]
Let's abandon this PR. New PR is ready to roll.

**Pull request closed without merging**
