### PR TITLE
fix: check both static list and remote list before raising error

### PR DESCRIPTION
**Pull request by aaliakseyenka**
@alexandercerutti please take a look on this MR. My case: I don't have anything in pass folder beside my `pass.json` file. All required icons I do using `load` API since icons are different for different events. In current master version I am getting error, although I specify all required data

### CODE REVIEW

**Comment by alexandercerutti** [comment]
Let me understand better. So you are downloading the icon every time you are creating a pass, based on the type of the pass. So you are saying that a check on remote files that were loaded is missing, aren't you? So if we don't check loaded files, if you don't have any files in your model except `pass.json` (which get excluded), you are getting `MODEL_UNINITIALIZED` error. Did I get the point?

**Comment by aaliakseyenka** [comment]
you are right

**Comment by alexandercerutti** [comment]
Perfect, I'll merge it asap, and release it in 1.5.8 (which is already ready to be released 👍). Then be sure to update to 1.6.0 as I'll release it: I'm going to add a planty of new fields introduced in iOS 12. 😉

**Comment by aaliakseyenka** [comment]
so technically, I would like to have better control on what can be loaded dynamically and what should be static.
Also, question: do you handle the case when we have icon.png in static and also trying to load it dynamically, but call fails. Do you have this fallback to use static instead of dynamic?

**Comment by aaliakseyenka** [comment]
>I'm going to add a planty of new fields introduced in iOS 12. 
do you have a link, describing new field? :)

**Comment by alexandercerutti** [comment]
About the fields, here you are:
https://developer.apple.com/documentation/passkit/wallet/supporting_semantic_tags_in_wallet_passes

Also there is one more called "row" valid only for auxiliaryFields, but it is undocumented yet (found in wwdc video).

About the fallback, if I remember correctly, the downloaded medias have priority respect static medias. But if the download fails, it won't be inserted inside remote files/remote buffers.

**Comment by alexandercerutti** [comment]
Published in [1.5.8](/alexandercerutti/passkit-generator/commit/1c8cf666fb340d66e4f53794a94f52f08f32a748) 🎉🎉🎉

**Pull request merged**
