### PR TITLE
fix: complete pass field types for typescript

### PR DESCRIPTION
**Pull request by Songkeys**
Added more static types.

### CODE REVIEW

**Review by alexandercerutti — CHANGES_REQUESTED** [review]
That's an interesting change.
I'd ask you to rename the fields to be compliant with the names.

So, for example:

`PKDataDetectorTypePhoneNumber` means `PKDataDetectionType` and not `FieldDataDetectorType`.

**Comment by Songkeys** [comment]
Sure. PTAL.

In the meantime, I highly recommend [`zod` as a great alternative to `joi`](https://zod.dev/?id=joi). It offers static type inference, so you don't have to manually write them out.

**Comment by Songkeys** [comment]
Interesting. I didn't know this since I've never used type checking to this level. Looks like they are going to introduce `switch` for this. Let wait and see. Great to learn something today!

**Review by alexandercerutti — APPROVED** [review]
LGTM! Thank you 🚀

**Pull request merged**
