### PR TITLE
feat: add description to override supported fields

### PR DESCRIPTION
**Pull request by aaliakseyenka**
Description field should be in the list since ticket passes should contain dynamic texts

### CODE REVIEW

**Comment by aaliakseyenka** [comment]
@alexandercerutti please take a look on this. Would be great if you could include it in the nearest version

**Comment by alexandercerutti** [comment]
Mhh, why should you be able to edit the description? Basically, if you have one type of pass, the description will be one. Moreover, if you have a localized pass, `description` is a Localized String. That mean that if you use `.localize` method, you can insert in description a placeholder that will be replaced in runtime by passkit with the description provided.

**Comment by aaliakseyenka** [comment]
One type - event ticket for concerts. But we may have several tickets for different concerts. User may buy two tickets for two different concerts and based on Apple guidelines we need to show different description like one with date of first event and another with date of another event and also adding respective name of events

**Comment by alexandercerutti** [comment]
Never heard this! Can you please link me that guideline?
Anyway, you are convincing me. 😁

**Comment by alexandercerutti** [comment]
Published in v1.5.6! Thank you @aaliakseyenka

**Pull request merged**
